# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42b7226123d082173dab66ea9b54ca9bfccd8fb05e202fe3b91c63d201ca70c3e5acea54d6cb7575defcfbefcde8ad359e6d5e5a0326cc4fc1ce59477180f6e4

test:
  secret_key_base: e1ea41d005c25b050d0a4be80bb0ec86f2e5f2c499e3dc20f41565c0b31a3c82124a4d58082f808b2d93ab594942c8c7e4a8da7cf24aed59862d2d68e812786e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
